export const coreStructuralContracts = [
  'NODUOS.CORE.CORE_AUTHORIZATION.v1',
  'NODUOS.CORE.AUTHORIZATION_DECISION.v1',
  'NODUOS.CORE.RESOURCE_REFERENCE.v1',
  'NODUOS.CORE.CONTEXT.v1',
  'NODUOS.CORE.TENANT.v1',
  'NODUOS.CORE.USER_ACCOUNT_REFERENCE.v1',
  'NODUOS.CORE.PERMISSION_GRANT.v1',
  'NODUOS.CORE.INHERITANCE_GRANT.v1',
  'NODUOS.CORE.AUDIT_LOG.v1',
  'NODUOS.CORE.EVENT_CONTRACT.v1'
] as const;

export type CoreStructuralContractId = typeof coreStructuralContracts[number];
